<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ClosurePeriodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('closure_periods')->insert([
            // Past closure periods (active) - 5 records
            [
                'start_date' => Carbon::now()->subDays(90)->format('Y-m-d'),
                'end_date' => Carbon::now()->subDays(88)->format('Y-m-d'),
                'reason' => 'New Year Holiday',
                'status' => 'active',
                'deleted_at' => null,
                'created_at' => Carbon::now()->subDays(95),
                'updated_at' => Carbon::now()->subDays(95),
            ],
            [
                'start_date' => Carbon::now()->subDays(60)->format('Y-m-d'),
                'end_date' => Carbon::now()->subDays(55)->format('Y-m-d'),
                'reason' => 'System Upgrade',
                'status' => 'active',
                'deleted_at' => null,
                'created_at' => Carbon::now()->subDays(65),
                'updated_at' => Carbon::now()->subDays(65),
            ],
            [
                'start_date' => Carbon::now()->subDays(30)->format('Y-m-d'),
                'end_date' => Carbon::now()->subDays(28)->format('Y-m-d'),
                'reason' => 'Holiday Break',
                'status' => 'active',
                'deleted_at' => null,
                'created_at' => Carbon::now()->subDays(35),
                'updated_at' => Carbon::now()->subDays(35),
            ],
            [
                'start_date' => Carbon::now()->subDays(15)->format('Y-m-d'),
                'end_date' => Carbon::now()->subDays(10)->format('Y-m-d'),
                'reason' => 'Facility Maintenance',
                'status' => 'active',
                'deleted_at' => null,
                'created_at' => Carbon::now()->subDays(20),
                'updated_at' => Carbon::now()->subDays(20),
            ],
            [
                'start_date' => Carbon::now()->subDays(5)->format('Y-m-d'),
                'end_date' => Carbon::now()->subDays(3)->format('Y-m-d'),
                'reason' => 'Emergency Repairs',
                'status' => 'active',
                'deleted_at' => null,
                'created_at' => Carbon::now()->subDays(8),
                'updated_at' => Carbon::now()->subDays(8),
            ],
            
            // Future closure periods (pending) - 20 records
            [
                'start_date' => Carbon::now()->addDays(7)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(9)->format('Y-m-d'),
                'reason' => 'Scheduled Maintenance',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(14)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(16)->format('Y-m-d'),
                'reason' => 'Equipment Inspection',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(21)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(23)->format('Y-m-d'),
                'reason' => 'Staff Training Day',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(28)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(30)->format('Y-m-d'),
                'reason' => 'Quarterly Inventory',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(35)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(37)->format('Y-m-d'),
                'reason' => 'HVAC System Maintenance',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(42)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(44)->format('Y-m-d'),
                'reason' => 'Fire Safety Inspection',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(49)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(51)->format('Y-m-d'),
                'reason' => 'Network Infrastructure Upgrade',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(56)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(58)->format('Y-m-d'),
                'reason' => 'Security System Update',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(63)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(65)->format('Y-m-d'),
                'reason' => 'Plumbing Maintenance',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(70)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(72)->format('Y-m-d'),
                'reason' => 'Electrical System Check',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(77)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(79)->format('Y-m-d'),
                'reason' => 'Building Exterior Cleaning',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(84)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(86)->format('Y-m-d'),
                'reason' => 'Furniture Replacement',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(91)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(93)->format('Y-m-d'),
                'reason' => 'Annual Deep Cleaning',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(98)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(100)->format('Y-m-d'),
                'reason' => 'Pest Control Service',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(105)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(107)->format('Y-m-d'),
                'reason' => 'Roof Inspection and Repair',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(112)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(114)->format('Y-m-d'),
                'reason' => 'Parking Lot Maintenance',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(119)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(121)->format('Y-m-d'),
                'reason' => 'Landscaping and Grounds Work',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(126)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(128)->format('Y-m-d'),
                'reason' => 'Audio Visual Equipment Upgrade',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(133)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(135)->format('Y-m-d'),
                'reason' => 'Backup Generator Testing',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'start_date' => Carbon::now()->addDays(140)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(142)->format('Y-m-d'),
                'reason' => 'Window Cleaning and Repair',
                'status' => 'pending',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Archived closure periods (soft deleted) - 8 records
            [
                'start_date' => Carbon::now()->subDays(180)->format('Y-m-d'),
                'end_date' => Carbon::now()->subDays(178)->format('Y-m-d'),
                'reason' => 'Old System Migration',
                'status' => 'active',
                'deleted_at' => Carbon::now()->subDays(175),
                'created_at' => Carbon::now()->subDays(185),
                'updated_at' => Carbon::now()->subDays(175),
            ],
            [
                'start_date' => Carbon::now()->subDays(150)->format('Y-m-d'),
                'end_date' => Carbon::now()->subDays(148)->format('Y-m-d'),
                'reason' => 'Cancelled: Weather Concerns',
                'status' => 'pending',
                'deleted_at' => Carbon::now()->subDays(145),
                'created_at' => Carbon::now()->subDays(155),
                'updated_at' => Carbon::now()->subDays(145),
            ],
            [
                'start_date' => Carbon::now()->subDays(120)->format('Y-m-d'),
                'end_date' => Carbon::now()->subDays(118)->format('Y-m-d'),
                'reason' => 'Cancelled: Vendor Unavailable',
                'status' => 'pending',
                'deleted_at' => Carbon::now()->subDays(115),
                'created_at' => Carbon::now()->subDays(125),
                'updated_at' => Carbon::now()->subDays(115),
            ],
            [
                'start_date' => Carbon::now()->subDays(100)->format('Y-m-d'),
                'end_date' => Carbon::now()->subDays(98)->format('Y-m-d'),
                'reason' => 'Outdated Renovation Plan',
                'status' => 'active',
                'deleted_at' => Carbon::now()->subDays(95),
                'created_at' => Carbon::now()->subDays(105),
                'updated_at' => Carbon::now()->subDays(95),
            ],
            [
                'start_date' => Carbon::now()->subDays(75)->format('Y-m-d'),
                'end_date' => Carbon::now()->subDays(73)->format('Y-m-d'),
                'reason' => 'Duplicate Entry Removed',
                'status' => 'pending',
                'deleted_at' => Carbon::now()->subDays(70),
                'created_at' => Carbon::now()->subDays(80),
                'updated_at' => Carbon::now()->subDays(70),
            ],
            [
                'start_date' => Carbon::now()->addDays(200)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(202)->format('Y-m-d'),
                'reason' => 'Cancelled: Budget Constraints',
                'status' => 'pending',
                'deleted_at' => Carbon::now()->subDays(5),
                'created_at' => Carbon::now()->subDays(10),
                'updated_at' => Carbon::now()->subDays(5),
            ],
            [
                'start_date' => Carbon::now()->addDays(250)->format('Y-m-d'),
                'end_date' => Carbon::now()->addDays(252)->format('Y-m-d'),
                'reason' => 'Cancelled: Schedule Conflict',
                'status' => 'pending',
                'deleted_at' => Carbon::now()->subDays(2),
                'created_at' => Carbon::now()->subDays(8),
                'updated_at' => Carbon::now()->subDays(2),
            ],
            [
                'start_date' => Carbon::now()->subDays(45)->format('Y-m-d'),
                'end_date' => Carbon::now()->subDays(43)->format('Y-m-d'),
                'reason' => 'Incorrectly Scheduled',
                'status' => 'active',
                'deleted_at' => Carbon::now()->subDays(40),
                'created_at' => Carbon::now()->subDays(50),
                'updated_at' => Carbon::now()->subDays(40),
            ],
        ]);
    }
}
